name = "avrada_examples_debounce"
description = "Sample application in Ada for AVR microcontrollers, debounce"
version = "0.1.0-dev"

authors = ["Rolf Ebert"]
maintainers = ["Rolf Ebert <rolf.ebert.gcc@gmx.de>"]
maintainers-logins = ["RREE"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
website = "https://sourceforge.net/projects/avr-ada/"

project-files = ["debounce.gpr"]

[configuration.values]
avrada_rts.AVR_MCU = "attiny2313"
avrada_rts.Clock_Frequency = 8000000

[[depends-on]]
gnat_avr_elf = "^11"
avrada_rts = "^2"
avrada_mcu = "^2"
avrada_lib = "^2"

[[pins]]
avrada_rts = { path = "../../AVRAda_RTS" }
avrada_mcu = { path = "../../AVRAda_MCU" }
avrada_lib = { path = "../../AVRAda_Lib" }
