name = "avrada_examples_7_segment_display"
description = "Ada for AVR microcontrollers, 7 segment displays"
version = "1.0.1"

authors = ["Rolf Ebert"]
maintainers = ["Rolf Ebert <rolf.ebert.gcc@gmx.de>"]
maintainers-logins = ["RREE"]
licenses = "GPL-2.0-or-later WITH GCC-exception-3.1"
website = "https://sourceforge.net/projects/avr-ada/"
tags = ["avr", "embedded", "demo"]

project-files = ["seven_segment_disp.gpr"]

[configuration.values]
avrada_rts.AVR_MCU = "atmega328p"
avrada_rts.Clock_Frequency = 16000000
avrada_lib.Process_Timing_Events_In_Ticks = true

[[depends-on]]
gnat_avr_elf = "^11 | ^12.2"
avrada_rts = "^2.0.1"
avrada_mcu = "^2.0.1"
avrada_lib = "^2.0.1"
